export const DISPATCH_BATCH_ITEMS_PER_PAGE = 7;

export const STATUS_BADGE_VARIANTS = {
  "Sent to Laundry": "pending",
  "In Laundry": "purple",
  "Sent to Business": "ready",
  "Returned": "completed",
  "Delayed": "overdue",
};

export const laundryOptions = [
  { label: "Laundries", value: "all" },
  { label: "FreshCare Laundry", value: "FreshCare Laundry" },
  { label: "Prime Laundry Services", value: "Prime Laundry Services" },
  { label: "BlueStar Textile", value: "BlueStar Textile" },
  { label: "PrimeLinen Pro", value: "PrimeLinen Pro" },
  { label: "Meridian Clean Services", value: "Meridian Clean Services" },
];

export const statusOptions = [
  { label: "Status", value: "all" },
  { label: "Sent to Laundry", value: "Sent to Laundry" },
  { label: "In Laundry", value: "In Laundry" },
  { label: "Sent to Business", value: "Sent to Business" },
  { label: "Returned", value: "Returned" },
  { label: "Delayed", value: "Delayed" },
];

export const INITIAL_DISPATCH_BATCHES = [
  {
    id: "BATCH-1024",
    laundryName: "FreshCare Laundry",
    dispatchLocation: "Main Site",
    created: "Jun 29, 2026, 10:30 AM",
    items: 120,
    status: "Sent to Laundry",
    createdBy: "Sarah Khan",
    driverName: "Kashif Mahmood",
    vehicleNumber: "LEA-4921",
    estimatedReturn: "Jul 01, 2026",
    notes: "Regular weekly linen supply batch.",
  },
  {
    id: "BATCH-1023",
    laundryName: "Prime Laundry Services",
    dispatchLocation: "North Site",
    created: "Jun 28, 2026, 04:15 PM",
    items: 86,
    status: "In Laundry",
    createdBy: "Ahmed Ali",
    driverName: "Tariq Jameel",
    vehicleNumber: "KHI-8832",
    estimatedReturn: "Jun 30, 2026",
    notes: "High-priority bath towels wash.",
  },
  {
    id: "BATCH-1022",
    laundryName: "FreshCare Laundry",
    dispatchLocation: "Main Site",
    created: "Jun 27, 2026, 11:00 AM",
    items: 154,
    status: "Sent to Business",
    createdBy: "Sarah Khan",
    driverName: "Kashif Mahmood",
    vehicleNumber: "LEA-4921",
    estimatedReturn: "Jun 29, 2026",
    notes: "Linen returned and dispatched back to business main store.",
  },
  {
    id: "BATCH-1021",
    laundryName: "BlueStar Textile",
    dispatchLocation: "East Wing",
    created: "Jun 26, 2026, 09:45 AM",
    items: 63,
    status: "Returned",
    createdBy: "Rania Aziz",
    driverName: "Bilal Hassan",
    vehicleNumber: "ISL-1002",
    estimatedReturn: "Jun 28, 2026",
    notes: "Delivered and verified at East Wing reception.",
  },
  {
    id: "BATCH-1020",
    laundryName: "PrimeLinen Pro",
    dispatchLocation: "South Hub",
    created: "Jun 25, 2026, 02:00 PM",
    items: 98,
    status: "Delayed",
    createdBy: "James Okafor",
    driverName: "Usman Raza",
    vehicleNumber: "LHR-7721",
    estimatedReturn: "Jun 27, 2026",
    notes: "Delayed due to presser maintenance issue at facility.",
  },
  {
    id: "BATCH-1019",
    laundryName: "Meridian Clean Services",
    dispatchLocation: "West Block",
    created: "Jun 24, 2026, 08:30 AM",
    items: 44,
    status: "In Laundry",
    createdBy: "Priya Nair",
    driverName: "Rashid Minhas",
    vehicleNumber: "FSD-3091",
    estimatedReturn: "Jun 27, 2026",
    notes: "Special stain removal treatment underway.",
  },
  {
    id: "BATCH-1018",
    laundryName: "FreshCare Laundry",
    dispatchLocation: "Main Site",
    created: "Jun 23, 2026, 03:20 PM",
    items: 210,
    status: "Returned",
    createdBy: "Sarah Khan",
    driverName: "Kashif Mahmood",
    vehicleNumber: "LEA-4921",
    estimatedReturn: "Jun 25, 2026",
    notes: "Bulk bedsheet batch returned cleanly.",
  },
  {
    id: "BATCH-1017",
    laundryName: "BlueStar Textile",
    dispatchLocation: "North Site",
    created: "Jun 22, 2026, 10:00 AM",
    items: 115,
    status: "Sent to Laundry",
    createdBy: "Ahmed Ali",
    driverName: "Bilal Hassan",
    vehicleNumber: "ISL-1002",
    estimatedReturn: "Jun 24, 2026",
    notes: "Uniform and tablecloths dispatch.",
  },
  {
    id: "BATCH-1016",
    laundryName: "PrimeLinen Pro",
    dispatchLocation: "Main Site",
    created: "Jun 21, 2026, 01:15 PM",
    items: 75,
    status: "Delayed",
    createdBy: "Sarah Khan",
    driverName: "Usman Raza",
    vehicleNumber: "LHR-7721",
    estimatedReturn: "Jun 23, 2026",
    notes: "Weather delay on delivery route.",
  },
  {
    id: "BATCH-1015",
    laundryName: "FreshCare Laundry",
    dispatchLocation: "East Wing",
    created: "Jun 20, 2026, 09:00 AM",
    items: 180,
    status: "Delayed",
    createdBy: "James Okafor",
    driverName: "Kashif Mahmood",
    vehicleNumber: "LEA-4921",
    estimatedReturn: "Jun 22, 2026",
    notes: "Awaiting inspection approval.",
  },
];

export const getDispatchSummaryCounts = (batches = []) => {
  return {
    totalBatches: batches.length,
    sentToLaundry: batches.filter((b) => b.status === "Sent to Laundry").length,
    inLaundry: batches.filter((b) => b.status === "In Laundry").length,
    returned: batches.filter((b) => b.status === "Returned" || b.status === "Sent to Business").length,
    delayed: batches.filter((b) => b.status === "Delayed").length,
  };
};
