export const laundries = [
  {
    id: "LND-001",
    name: "PureWash Industrial",
    contact: "Marcus Webb",
    email: "marcus@purewash.co",
    location: "Chicago, IL",
    status: "Connected",
    statusVariant: "success",
    isDefault: true,
    batches: 3,
    itemsSent: 229,
    missing: 8,
  },
  {
    id: "LND-002",
    name: "CleanFlow Solutions",
    contact: "Sarah Okafor",
    email: "sarah@cleanflow.io",
    location: "Evanston, IL",
    status: "Connected",
    statusVariant: "success",
    isDefault: false,
    batches: 1,
    itemsSent: 88,
    missing: 1,
  },
  {
    id: "LND-003",
    name: "Metro Linen Services",
    contact: "Tom Hayashi",
    email: "tom@metrolinen.com",
    location: "Oak Park, IL",
    status: "Connected",
    statusVariant: "success",
    isDefault: false,
    batches: 2,
    itemsSent: 65,
    missing: 0,
  },
  {
    id: "LND-006",
    name: "Riverside Linen Works",
    contact: "Lisa Petrov",
    email: "lisa@riverlinens.net",
    location: "Joliet, IL",
    status: "Suspended",
    statusVariant: "neutral",
    isDefault: false,
    batches: 0,
    itemsSent: 0,
    missing: 0,
  },
];

export const pendingRequests = [
  {
    id: 1,
    email: "freshlaundry@gmail.com",
    status: "Invite Sent",
    statusVariant: "neutral",
    sentAt: "Invite sent 2d ago",
  },
  {
    id: 2,
    email: "Sparkclean@gmail.com",
    status: "Invite Sent",
    statusVariant: "neutral",
    sentAt: "Invite sent 2d ago",
  },
];
