import { Bell, Clock3, MapPin, Radio, Smartphone, User } from "lucide-react";

export const scannerDetailsData = {
  "SCN-ENT-001": {
    id: "SCN-ENT-001",
    name: "Main Entrance",
    type: "Fixed",
    mode: "Entry",
    status: "Active",
    location: "Lobby - Floor 1",
    operator: "Alex Torres",
    lastScan: "2 min ago",
    recentReads: 312,
    zone: "Main Lobby",
    firmware: "v2.7.4",
    deviceId: "DEV-ENT-104",
    connectedLaundry: "Front Desk Hub",
    exceptionCount: 0,
  },
  "SCN-EXT-002": {
    id: "SCN-EXT-002",
    name: "Loading Bay Exit",
    type: "Fixed",
    mode: "Exit",
    status: "Active",
    location: "Warehouse - Floor G",
    operator: "Maria Santos",
    lastScan: "7 min ago",
    recentReads: 198,
    zone: "Service Exit",
    firmware: "v2.7.1",
    deviceId: "DEV-EXT-221",
    connectedLaundry: "Warehouse Dock",
    exceptionCount: 1,
  },
  "SCN-PRT-003": {
    id: "SCN-PRT-003",
    name: "Handheld Unit A",
    type: "Portable",
    mode: "Automatic",
    status: "Active",
    location: "Roaming",
    operator: "James Dawson",
    lastScan: "18 min ago",
    recentReads: 87,
    zone: "Mobile Device",
    firmware: "v1.9.8",
    deviceId: "DEV-PRT-302",
    connectedLaundry: "Field Operations",
    exceptionCount: 0,
  },
  "SCN-ENT-004": {
    id: "SCN-ENT-004",
    name: "Laundry Room Entry",
    type: "Fixed",
    mode: "Entry",
    status: "Warning",
    location: "Laundry - Floor 2",
    operator: "Sarah Kim",
    lastScan: "1 hr ago",
    recentReads: 44,
    zone: "Laundry Corridor",
    firmware: "v2.6.9",
    deviceId: "DEV-ENT-118",
    connectedLaundry: "Laundry Floor 2",
    exceptionCount: 3,
  },
  "SCN-PRT-005": {
    id: "SCN-PRT-005",
    name: "Handheld Unit B",
    type: "Portable",
    mode: "Automatic",
    status: "Inactive",
    location: "Roaming",
    operator: "Unassigned",
    lastScan: "3 hrs ago",
    recentReads: 0,
    zone: "Mobile Device",
    firmware: "v1.8.2",
    deviceId: "DEV-PRT-305",
    connectedLaundry: "Field Operations",
    exceptionCount: 2,
  },
  "SCN-EXT-006": {
    id: "SCN-EXT-006",
    name: "Staff Exit Gate",
    type: "Fixed",
    mode: "Exit",
    status: "Inactive",
    location: "Staff Corridor - Floor 1",
    operator: "Unassigned",
    lastScan: "2 days ago",
    recentReads: 0,
    zone: "Staff Corridor",
    firmware: "v2.5.4",
    deviceId: "DEV-EXT-244",
    connectedLaundry: "North Wing",
    exceptionCount: 1,
  },
};

export const scannerSummaryCards = [
  { key: "lastScan", label: "Last Scan", icon: Clock3 },
  { key: "recentReads", label: "Recent Reads", icon: Bell },
  { key: "location", label: "Location", icon: MapPin },
  { key: "operator", label: "Operator", icon: User },
];

export const scannerDeviceFields = [
  { key: "deviceId", label: "Device ID" },
  { key: "firmware", label: "Firmware" },
  { key: "zone", label: "Zone" },
  { key: "connectedLaundry", label: "Connected Laundry" },
];

export const scannerLogRows = [
  {
    id: "LOG-001",
    tagId: "TAG-001",
    asset: "King Duvet Cover",
    assetId: "LNS-BED-041",
    zone: "Lobby",
    mode: "Automatic",
    batch: "BTH-20240611-001",
    items: 229,
    status: "In Laundry",
    lastActivity: "2 min ago",
    statusVariant: "purple",
  },
  {
    id: "LOG-002",
    tagId: "TAG-002",
    asset: "CleanFlow Solutions",
    assetId: "LND-002",
    zone: "Evanston, IL",
    mode: "Check In",
    batch: "BTH-20240611-001",
    items: 88,
    status: "Returned",
    lastActivity: "1 hr ago",
    statusVariant: "info",
  },
  {
    id: "LOG-003",
    tagId: "TAG-003",
    asset: "Metro Linen Services",
    assetId: "LND-003",
    zone: "Oak Park, IL",
    mode: "Automatic",
    batch: "BTH-20240611-001",
    items: 65,
    status: "In Business",
    lastActivity: "3 hrs ago",
    statusVariant: "success",
  },
  {
    id: "LOG-004",
    tagId: "TAG-004",
    asset: "Riverside Linen Works",
    assetId: "LND-006",
    zone: "Joliet, IL",
    mode: "Check Out",
    batch: "BTH-20240611-001",
    items: 0,
    status: "Sent to Laundry",
    lastActivity: "Suspended",
    statusVariant: "warning",
  },
];