export const delayedTrend = [8, 12, 6, 20, 14, 18, 24, 32];

export const delayedWeekLabels = [
  "W18",
  "W19",
  "W20",
  "W21",
  "W22",
  "W23",
  "W24",
  "W25",
];

export const delayedAssets = [
  {
    id: "LNS-BED-0099",
    name: "Pillow Case Set",
    category: "Bed Linen",
    categoryVariant: "info",
    laundry: "PureWash Industrial",
    batchId: "BTH-20240607-009",
    daysDelayed: 6,
    lastScannedDate: "Jun 9",
    lastScannedTime: "15:00",
  },
  {
    id: "LNS-TWL-0433",
    name: "Face Cloth",
    category: "Bath Towels",
    categoryVariant: "purple",
    laundry: "CleanFlow Solutions",
    batchId: "BTH-20240528-004",
    daysDelayed: 15,
    lastScannedDate: "May 30",
    lastScannedTime: "09:00",
    critical: true,
  },
  {
    id: "LNS-UNF-0101",
    name: "Kitchen Chef Coat",
    category: "Uniforms",
    categoryVariant: "info",
    laundry: "PureWash Industrial",
    batchId: "BTH-20240607-009",
    daysDelayed: 5,
    lastScannedDate: "Jun 8",
    lastScannedTime: "11:22",
  },
  {
    id: "LNS-TBL-0111",
    name: "Round Tablecloth",
    category: "Table Linen",
    categoryVariant: "info",
    laundry: "Metro Linen Services",
    batchId: "BTH-20240620-017",
    daysDelayed: 3,
    lastScannedDate: "Jun 10",
    lastScannedTime: "08:40",
  },
  {
    id: "LNS-BED-0041",
    name: "King Duvet Cover",
    category: "Bed Linen",
    categoryVariant: "info",
    laundry: "PureWash Industrial",
    batchId: "BTH-20240611-001",
    daysDelayed: 1,
    lastScannedDate: "Jun 11",
    lastScannedTime: "10:30",
  },
];
