export const categories = [
  {
    id: "CAT-007",
    name: "Kitchen Cloths",
    status: "Inactive",
    statusVariant: "neutral",
    usage: "Not in Use",
    usageState: "unused",
    assets: null,
    created: "May 15, 2025",
    lastUpdated: "May 15, 2025",
  },
  {
    id: "CAT-006",
    name: "Spa Robes",
    status: "Inactive",
    statusVariant: "neutral",
    usage: "Not in Use",
    usageState: "unused",
    assets: null,
    created: "Apr 2, 2025",
    lastUpdated: "Apr 2, 2025",
  },
  {
    id: "CAT-005",
    name: "Pool Towels",
     status: "Active",
    statusVariant: "success",
    usage: "In Use",
    usageState: "used",
    assets: 95,
    created: "Mar 8, 2025",
    lastUpdated: "Jun 1, 2025",
  },
  {
    id: "CAT-004",
    name: "Table Linen",
    status: "Active",
    statusVariant: "success",
    usage: "In Use",
    usageState: "used",
    assets: 203,
    created: "Feb 14, 2025",
    lastUpdated: "Jun 5, 2025",
  },
  {
    id: "CAT-003",
    name: "Staff Uniforms",
    status: "Active",
    statusVariant: "success",
    usage: "In Use",
    usageState: "used",
    assets: 178,
    created: "Feb 3, 2025",
    lastUpdated: "May 28, 2025",
  },
  {
    id: "CAT-002",
    name: "Bath Towels",
    status: "Active",
    statusVariant: "success",
    usage: "In Use",
    usageState: "used",
    assets: 289,
    created: "Jan 12, 2025",
    lastUpdated: "Jun 9, 2025",
  },
  {
    id: "CAT-001",
    name: "Bed Linen",
    status: "Active",
    statusVariant: "success",
    usage: "In Use",
    usageState: "used",
    assets: 412,
    created: "Jan 12, 2025",
    lastUpdated: "Jun 10, 2025",
  },
  {
    id: "CAT-000",
    name: "Bed Linen",
    status: "Inactive",
    statusVariant: "neutral",
    usage: "Not in Use",
    usageState: "unused",
    assets: 412,
    created: "Jan 12, 2025",
    lastUpdated: "Jun 10, 2025",
  },
];
