export const getMockBatchDetails = (batchId = "BATCH-1024") => {
  return {
    id: batchId,
    status: "Dispatched",
    statusVariant: "info",
    lastActivity: "5 minutes ago",
    selectedLaundry: "FreshCare Laundry",
    dispatchLocation: "Main Site",
    createdBy: "Sarah Khan",
    dispatchDateTime: "Jun 29, 2026, 10:30 AM",
    summary: {
      totalItems: 98,
      unlinkedTags: 2,
      checkedInLaundry: 0,
      itemsReturned: 0,
      delayed: 0,
    },
    lifecycle: [
      {
        id: "scanning",
        label: "Scanning",
        time: "Jun 29, 10:24 AM",
        state: "completed",
      },
      {
        id: "created",
        label: "Batch Created",
        time: "Jun 29, 10:29 AM",
        state: "completed",
      },
      {
        id: "dispatched",
        label: "Dispatched",
        time: "Jun 29, 10:30 AM",
        state: "active",
      },
      {
        id: "in_laundry",
        label: "In Laundry",
        time: "Pending",
        state: "pending",
      },
      {
        id: "sent_to_business",
        label: "Sent to Business",
        time: "Pending",
        state: "pending",
      },
      {
        id: "returned",
        label: "Returned",
        time: "Pending",
        state: "pending",
      },
    ],
    categoryBreakdown: [
      {
        category: "Towels",
        count: 60,
        percentage: 61,
        variant: "teal",
      },
      {
        category: "Bedsheets",
        count: 24,
        percentage: 24,
        variant: "purple",
      },
      {
        category: "Pillow Covers",
        count: 14,
        percentage: 15,
        variant: "indigo",
      },
    ],
    laundryPartner: {
      name: "FreshCare Laundry",
      status: "Active Partner",
      contact: "Marcus Webb",
      phone: "+1 (555) 812-4490",
      email: "ops@freshcare.com",
      location: "Main Site, Downtown",
    },
    notes: "Urgent run — pre-event linens. Return expected by Jul 2, 2026.",
    latestActivity: [
      {
        id: "act-1",
        title: "Bulk Scan Session Started",
        meta: "System • 2026",
      },
      {
        id: "act-2",
        title: "Laundry Selected",
        meta: "Sarah Khan • 2026",
      },
      {
        id: "act-3",
        title: "98 Existing Tags Scanned",
        meta: "System • 2026",
      },
    ],
    items: [
      {
        id: 1,
        epc: "000209A3F1B001...",
        assetName: "Bath Towel Large",
        assetId: "AST-4821",
        category: "Towels",
        currentStatus: "Sent to Laundry",
        lastScan: "10:30 AM",
        lastLocation: "Main Site Gate",
        itemProgress: "Sent to Laundry",
      },
      {
        id: 2,
        epc: "000209A3F1B002...",
        assetName: "Chef Jacket XL",
        assetId: "AST-3302",
        category: "Uniforms",
        currentStatus: "Sent to Laundry",
        lastScan: "10:30 AM",
        lastLocation: "Main Site Gate",
        itemProgress: "Sent to Business",
      },
      {
        id: 3,
        epc: "000209A3F1B003...",
        assetName: "White Duvet Cover",
        assetId: "AST-7741",
        category: "Bedsheets",
        currentStatus: "Sent to Laundry",
        lastScan: "10:30 AM",
        lastLocation: "Main Site Gate",
        itemProgress: "Returned",
      },
      {
        id: 4,
        epc: "000209A3F1B004...",
        assetName: "Hand Towel Medium",
        assetId: "AST-5512",
        category: "Towels",
        currentStatus: "In Laundry",
        lastScan: "11:15 AM",
        lastLocation: "FreshCare — Entry",
        itemProgress: "In Laundry",
      },
      {
        id: 5,
        epc: "000209A3F1B005...",
        assetName: "Pillow Case Standard",
        assetId: "AST-6634",
        category: "Pillow Covers",
        currentStatus: "Sent to Laundry",
        lastScan: "10:30 AM",
        lastLocation: "Main Site Gate",
        itemProgress: "Sent to Laundry",
      },
      {
        id: 6,
        epc: "000209A3F1B006...",
        assetName: "Bath Robe White",
        assetId: "AST-2218",
        category: "Towels",
        currentStatus: "Sent to Laundry",
        lastScan: "10:30 AM",
        lastLocation: "Main Site Gate",
        itemProgress: "Sent to Laundry",
      },
      {
        id: 7,
        epc: "000209A3F1B007...",
        assetName: "Table Cloth 60x90",
        assetId: "AST-9901",
        category: "Bedsheets",
        currentStatus: "Delayed",
        lastScan: "10:30 AM",
        lastLocation: "Main Site Gate",
        itemProgress: "Delayed",
      },
      {
        id: 8,
        epc: "000209A3F1B008...",
        assetName: "Waiter Apron Black",
        assetId: "AST-4490",
        category: "Uniforms",
        currentStatus: "Sent to Laundry",
        lastScan: "10:30 AM",
        lastLocation: "Main Site Gate",
        itemProgress: "Sent to Laundry",
      },
      {
        id: 9,
        epc: "000209A3F1B009...",
        assetName: "Floor Mat Anti-Slip",
        assetId: "AST-8832",
        category: "Towels",
        currentStatus: "Sent to Laundry",
        lastScan: "10:30 AM",
        lastLocation: "Main Site Gate",
        itemProgress: "Sent to Laundry",
      },
      {
        id: 10,
        epc: "000209A3F1B010...",
        assetName: "Spa Robe Beige",
        assetId: "AST-5501",
        category: "Towels",
        currentStatus: "In Laundry",
        lastScan: "11:15 AM",
        lastLocation: "FreshCare — Entry",
        itemProgress: "In Laundry",
      },
    ],
    fullActivityLog: [
      {
        id: "log-1",
        event: "Bulk Scan Session Started",
        user: "System",
        userType: "system",
        timestamp: "Jun 29, 2026, 10:20 AM",
        details: "Bulk scan initiated on Gate Scanner A1 (SC-001) at Main Site.",
        iconType: "system",
      },
      {
        id: "log-2",
        event: "Laundry Selected",
        user: "Sarah Khan",
        userType: "user",
        timestamp: "Jun 29, 2026, 10:21 AM",
        details: "FreshCare Laundry selected as dispatch partner.",
        iconType: "user",
      },
      {
        id: "log-3",
        event: "98 Existing Tags Scanned",
        user: "System",
        userType: "system",
        timestamp: "Jun 29, 2026, 10:24 AM",
        details: "98 existing linked tags detected and validated.",
        iconType: "system",
      },
      {
        id: "log-4",
        event: "2 New Unlinked Tags Detected",
        user: "System",
        userType: "system",
        timestamp: "Jun 29, 2026, 10:24 AM",
        details: "Tags F390...001 and F390...002 are new and not linked to any asset.",
        iconType: "system",
      },
      {
        id: "log-5",
        event: "3 Exceptions Raised",
        user: "System",
        userType: "system",
        timestamp: "Jun 29, 2026, 10:23 AM",
        details: "Detached tag, retired tag, and unreadable EPC flagged as exceptions.",
        iconType: "warning",
      },
      {
        id: "log-6",
        event: "Category Assigned to New Tag",
        user: "Sarah Khan",
        userType: "user",
        timestamp: "Jun 29, 2026, 10:26 AM",
        details: "Category 'Towels' assigned to tag F390...002.",
        iconType: "user",
      },
      {
        id: "log-7",
        event: "Batch Created",
        user: "Sarah Khan",
        userType: "user",
        timestamp: "Jun 29, 2026, 10:29 AM",
        details: "Dispatch batch BATCH-1024 created with 98 valid items.",
        iconType: "success",
      },
      {
        id: "log-8",
        event: "Batch Dispatched",
        user: "Sarah Khan",
        userType: "user",
        timestamp: "Jun 29, 2026, 10:30 AM",
        details: "Batch confirmed and dispatched to FreshCare Laundry, Main Site.",
        iconType: "success",
      },
      {
        id: "log-9",
        event: "Exception EXC-0039 Resolved",
        user: "Ahmed Ali",
        userType: "user",
        timestamp: "Jun 29, 2026, 10:45 AM",
        details: "Unreadable EPC confirmed as damaged hardware — tag decommissioned.",
        iconType: "success",
      },
    ],
  };
};
