export const staffMembers = [
  {
    id: "STF-001",
    initials: "SM",
    name: "Sarah Mitchell",
    email: "sarah.mitchell@clothsync.com",
    phone: "+1 (555) 201-4823",
    role: "Operations Manager",
    location: "Downtown Hub",
    permission: "Full Access",
    permissionVariant: "info",
    status: "Active",
    statusVariant: "success",
    lastActive: "2 min ago",
    avatarVariant: "info",
  },
  {
    id: "STF-002",
    initials: "JO",
    name: "James Okafor",
    email: "james.okafor@clothsync.com",
    phone: "+1 (555) 387-9134",
    role: "Inventory Analyst",
    location: "West Side Depot",
    permission: "Limited Access",
    permissionVariant: "neutral",
    status: "Active",
    statusVariant: "success",
    lastActive: "1 hr ago",
    avatarVariant: "purple",
  },
  {
    id: "STF-003",
    initials: "PN",
    name: "Priya Nair",
    email: "priya.nair@clothsync.com",
    phone: "+1 (555) 412-6671",
    role: "Admin",
    location: "All Locations",
    permission: "Admin",
    permissionVariant: "purple",
    status: "Active",
    statusVariant: "success",
    lastActive: "3 hrs ago",
    avatarVariant: "success",
  },
  {
    id: "STF-004",
    initials: "DC",
    name: "David Chu",
    email: "david.chu@clothsync.com",
    phone: "+1 (555) 564-2290",
    role: "Dispatch Coordinator",
    location: "North Branch",
    permission: "Limited Access",
    permissionVariant: "neutral",
    status: "Inactive",
    statusVariant: "neutral",
    lastActive: "5 days ago",
    avatarVariant: "warning",
  },
  {
    id: "STF-005",
    initials: "LH",
    name: "Leila Hassan",
    email: "leila.hassan@clothsync.com",
    phone: "+1 (555) 700-3381",
    role: "Scanner Operator",
    location: "East End Facility",
    permission: "Limited Access",
    permissionVariant: "neutral",
    status: "Pending Invite",
    statusVariant: "warning",
    lastActive: "Never",
    avatarVariant: "danger",
  },
  {
    id: "STF-006",
    initials: "MW",
    name: "Marcus Webb",
    email: "marcus.webb@clothsync.com",
    phone: "+1 (555) 818-9902",
    role: "Reports Analyst",
    location: "Downtown Hub",
    permission: "Full Access",
    permissionVariant: "info",
    status: "Active",
    statusVariant: "success",
    lastActive: "Yesterday",
    avatarVariant: "info",
  },
  {
    id: "STF-007",
    initials: "TR",
    name: "Tanya Rossi",
    email: "tanya.rossi@clothsync.com",
    phone: "+1 (555) 923-5543",
    role: "Category Manager",
    location: "West Side Depot",
    permission: "Full Access",
    permissionVariant: "info",
    status: "Active",
    statusVariant: "success",
    lastActive: "4 hrs ago",
    avatarVariant: "purple",
  },
];

export const roleOptions = [
  { label: "Role", value: "all" },
  { label: "Operations Manager", value: "Operations Manager" },
  { label: "Inventory Analyst", value: "Inventory Analyst" },
  { label: "Admin", value: "Admin" },
  { label: "Dispatch Coordinator", value: "Dispatch Coordinator" },
  { label: "Scanner Operator", value: "Scanner Operator" },
  { label: "Reports Analyst", value: "Reports Analyst" },
  { label: "Category Manager", value: "Category Manager" },
];

export const statusOptions = [
  { label: "Status", value: "all" },
  { label: "Active", value: "Active" },
  { label: "Inactive", value: "Inactive" },
  { label: "Pending Invite", value: "Pending Invite" },
];

export const permissionOptions = [
  { label: "Permission", value: "all" },
  { label: "Full Access", value: "Full Access" },
  { label: "Limited Access", value: "Limited Access" },
  { label: "Admin", value: "Admin" },
];
