export const categoryRows = [
  {
    id: "bed-linen",
    category: "Bed Linen",
    totalAssets: 412,
    sent: 142,
    returned: 118,
    delayed: 8,
    missing: 3,
    returnRate: 83,
    averageWashes: 14,
  },
  {
    id: "bath-towels",
    category: "Bath Towels",
    totalAssets: 289,
    sent: 89,
    returned: 74,
    delayed: 12,
    missing: 4,
    returnRate: 83,
    averageWashes: 27,
  },
  {
    id: "uniforms",
    category: "Uniforms",
    totalAssets: 178,
    sent: 67,
    returned: 60,
    delayed: 1,
    missing: 0,
    returnRate: 90,
    averageWashes: 8,
  },
  {
    id: "table-linen",
    category: "Table Linen",
    totalAssets: 203,
    sent: 55,
    returned: 48,
    delayed: 0,
    missing: 0,
    returnRate: 87,
    averageWashes: 5,
  },
  {
    id: "pool-towels",
    category: "Pool Towels",
    totalAssets: 95,
    sent: 30,
    returned: 28,
    delayed: 0,
    missing: 2,
    returnRate: 93,
    averageWashes: 11,
  },
];

export const categoryChartSeries = [
  { key: "sent", label: "Sent", color: "var(--color-sky-blue)" },
  { key: "returned", label: "Returned", color: "var(--color-seafoam)" },
  { key: "delayed", label: "Delayed", color: "var(--color-pending)" },
];
