export const tagsData = [
    {
        id: "TAG-001",
        epc: "E2800189200040D6...",
        mapping: "Linked",
        assignedAsset: "King Duvet Cover",
        assetId: "LNS-BED-0041",
        category: "Bed Linen",
        assetStatus: "In Laundry",
        assetStatusVariant: "laundry",
        tagStatus: "Active",
        tagStatusVariant: "primary",
        lastScanTime: "2 min ago",
        location: "Laundry — Loading Bay",
        createdAt: "Jan 12, 2025",
    },
    {
        id: "TAG-002",
        epc: "E2800189200040D6...",
        mapping: "Linked",
        assignedAsset: "Bath Towel — Large",
        assetId: "LNS-TML-0198",
        category: "Bath Towels",
        assetStatus: "Sent to Laundry",
        assetStatusVariant: "sent",
        tagStatus: "Active",
        tagStatusVariant: "primary",
        lastScanTime: "7 min ago",
        location: "Loading Bay",
        createdAt: "Jan 12, 2025",
    },
    {
        id: "TAG-003",
        epc: "E2800189200040D6...",
        mapping: "Linked",
        assignedAsset: "Housekeeping Apron",
        assetId: "LNS-UNF-0067",
        category: "Staff Uniforms",
        assetStatus: "In Business",
        assetStatusVariant: "business",
        tagStatus: "Active",
        tagStatusVariant: "primary",
        lastScanTime: "1 hr ago",
        location: "Lobby — Floor 1",
        createdAt: "Feb 3, 2025",
    },
    {
        id: "TAG-004",
        epc: "E2800189200040D6...",
        mapping: "Linked",
        assignedAsset: "Pillow Case Set",
        assetId: "LNS-BED-0099",
        category: "Bed Linen",
        assetStatus: "Delayed",
        assetStatusVariant: "delayed",
        tagStatus: "Active",
        tagStatusVariant: "primary",
        lastScanTime: "3 hrs ago",
        location: "PureWash Industrial",
        hasAlert: true,
        createdAt: "Jan 14, 2025",
    },
    {
        id: "TAG-005",
        epc: "E2800189200040D6...",
        mapping: "Linked",
        assignedAsset: "Not mapped",
        assetId: "",
        category: "—",
        assetStatus: "—",
        assetStatusVariant: "secondary",
        tagStatus: "Active",
        tagStatusVariant: "primary",
        lastScanTime: "Never",
        location: "",
        createdAt: "Jun 5, 2025",
    },
    {
        id: "TAG-006",
        epc: "E2800189200040D6...",
        mapping: "Linked",
        assignedAsset: "Not mapped",
        assetId: "",
        category: "—",
        assetStatus: "—",
        assetStatusVariant: "secondary",
        tagStatus: "Active",
        tagStatusVariant: "primary",
        lastScanTime: "Never",
        location: "",
        createdAt: "Jun 5, 2025",
    },
    {
        id: "TAG-007",
        epc: "E2800189200040D6...",
        mapping: "Linked",
        assignedAsset: "Not mapped",
        assetId: "",
        category: "—",
        assetStatus: "—",
        assetStatusVariant: "secondary",
        tagStatus: "inactive",
        tagStatusVariant: "secondary",
        lastScanTime: "2 days ago",
        location: "Loading Bay",
        hasAlert: true,
        createdAt: "Mar 8, 2025",
    },
    {
        id: "TAG-008",
        epc: "E2800189200040D6...",
        mapping: "Linked",
        assignedAsset: "Not mapped",
        assetId: "",
        category: "—",
        assetStatus: "—",
        assetStatusVariant: "secondary",
        tagStatus: "inactive",
        tagStatusVariant: "secondary",
        lastScanTime: "14 days ago",
        location: "Lobby — Floor 1",
        createdAt: "Mar 8, 2025",
    },
];

export const allTagsOptions = [
    { label: "All Tags", value: "all" },
    { label: "Linked", value: "Linked" },
    { label: "Unlinked", value: "Unlinked" },
];

export const categoryOptions = [
    { label: "Categories", value: "all" },
    { label: "Bed Linen", value: "Bed Linen" },
    { label: "Bath Towels", value: "Bath Towels" },
    { label: "Staff Uniforms", value: "Staff Uniforms" },
];

export const assetStatusOptions = [
    { label: "Asset Status", value: "all" },
    { label: "In Laundry", value: "In Laundry" },
    { label: "Sent to Laundry", value: "Sent to Laundry" },
    { label: "In Business", value: "In Business" },
    { label: "Delayed", value: "Delayed" },
];

export const statusOptions = [
    { label: "Status", value: "all" },
    { label: "Active", value: "Active" },
    { label: "Inactive", value: "inactive" },
];
